Feature gateway/filter
Gaship/gaship-gateway pull request #2
Opened 2022-07-19 13:34 UTC by JoisFe

확인 부탁드려요

2022-07-19 15:32 UTC, oct-sky-out requested changes

2022-07-19 15:32 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipgateway/token/util/JwtTokenUtil.java
> +     * Gets payload from token.
자바독 작성 부탁드립니다!

2022-07-19 15:32 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipgateway/fliter/RequestFilter.java
> +    public static class Config {
Config 클래스를  inner class로 두신 특별한 이유가 있을까요?

2022-07-19 15:32 UTC, oct-sky-out commented on src/main/java/shop/gaship/gashipgateway/config/RouteLocatorConfig.java
> +                errorCode = 99;
이런건 옆에 에러코드가 무슨 에러를 의미하는지 "//" 주석을 첨부하는것도 독자입장에서는 좋은 주석이 될거같아요

2022-07-19 15:32 UTC, oct-sky-out commented on .github/workflows/maven-publish.yml
> +    branches: [ "development" ]
현재 테스트가 깨져서 빌드에 오류가납니다.  게이트웨이 테스트 한번 부탁드리고, 테스트 커버 부탁드립니다.

2022-07-20 00:25 UTC, JoisFe commented on src/main/java/shop/gaship/gashipgateway/config/RouteLocatorConfig.java
> +                errorCode = 99;
넵 주석 달도록 하겠습니다.

2022-07-20 00:27 UTC, JoisFe commented on .github/workflows/maven-publish.yml
> +    branches: [ "development" ]
게이트 웨이 테스트 코드를 작성하지 않았는데 main method 관련 기본 테스트 클래스로 인한 문제로 보입니다. 해당 클래스 삭제하도록 하겠습니다.

2022-07-20 00:27 UTC, JoisFe commented on src/main/java/shop/gaship/gashipgateway/token/util/JwtTokenUtil.java
> +     * Gets payload from token.
넵 자바독 부분 다시 작성하도록 하겠습니다.

2022-07-20 02:09 UTC, visualp commented on src/main/java/shop/gaship/gashipgateway/config/RouteLocatorConfig.java
> +                .uri("http://localhost:7073"))
서버주소는 하드코딩 보다는 properties쪽으로 빼는게 좋을거 같아요

2022-07-20 02:12 UTC, visualp commented on src/main/java/shop/gaship/gashipgateway/config/RouteLocatorConfig.java
> +            int errorCode = 999;
errorCode를 enu관리해보면 어떨까요?

2022-07-20 02:21 UTC, visualp commented on src/main/java/shop/gaship/gashipgateway/fliter/RequestFilter.java
> +                .build();
roles.toString() 형태로 전달될거 같아요. [ROLE_ADMIN,ROLE_USER]
String.join(",",list) 형태로 변경 해보는건 어떨가요? ROLE_ADMIN,ROLE_USER

2022-07-20 02:22 UTC, visualp commented on src/main/java/shop/gaship/gashipgateway/token/store/Payload.java
> +    private Long identificationNumber;
identificationNumber는 회원의 NO 인가요?
NO 보다는  일회성으로 식별할 수 있는 UUID 형태의 식별자를 넘겨주는거는 어떨까요?

2022-07-20 02:24 UTC, visualp commented on pom.xml
> +			<version>2.7.0</version>
특별한 이유가 없다면 version은 빼도 될거 같아요

2022-07-20 02:28 UTC, visualp commented on pom.xml
> +			<groupId>io.lettuce</groupId>
spring-data-readis -> spring-boot-starter-data-redis  사용해보세요

2022-07-20 02:40 UTC, visualp commented on src/main/java/shop/gaship/gashipgateway/config/RedisConfig.java
> +@ConfigurationProperties(prefix = "redis")
ignoreUnknownFields=true 붙여주면 더 좋을거 같아요

2022-07-20 02:41 UTC, visualp commented on src/main/java/shop/gaship/gashipgateway/config/RedisConfig.java
> +    private ClassLoader classLoader;
classLoader는 어디에 사용하는건가요?

2022-07-20 02:51 UTC, visualp commented on src/main/java/shop/gaship/gashipgateway/fliter/RequestFilter.java
> +            String accessToken = exchange.getRequest().getHeaders().get("X-AUTH-TOKEN").get(0);
X-AUTH-TOKEN으로 정한 이유가 있을까요?

2022-07-20 02:57 UTC, visualp commented on src/main/java/shop/gaship/gashipgateway/fliter/RequestFilter.java
> +                throw new LogoutTokenRequestException();
처음에 로그인전 상태(Accesstoken 없는 상태)에서 index page 접근하게 되면 토큰이 없는 상태일 텐데 .. 문제가 발생할 거 같아요.

2022-07-20 03:01 UTC, visualp commented on src/main/java/shop/gaship/gashipgateway/fliter/RequestFilter.java
> +            Payload payload = config.jwtTokenUtil.getPayloadFromToken(accessToken);
accessToken의 만료기간 체크가 필요할거 같아요.

2022-07-20 03:05 UTC, visualp reviewed
black list 체크해서 차단해주는 기능도 필요 할거같아요. 
수고하셨습니다.

2022-07-21 00:35 UTC, JoisFe commented on src/main/java/shop/gaship/gashipgateway/config/RouteLocatorConfig.java
> +            int errorCode = 999;
그렇게 관리하도록 하겠습니다.

2022-07-21 00:35 UTC, JoisFe commented on src/main/java/shop/gaship/gashipgateway/fliter/RequestFilter.java
> +                .build();
이 부분은 확인 후 문제가 있다면 해당 방식으로 수정하겠습니다.

2022-07-21 00:36 UTC, JoisFe commented on src/main/java/shop/gaship/gashipgateway/token/store/Payload.java
> +    private Long identificationNumber;
넵 회원의 NO인데 이 부분이 회원이 가입한 순서로 짐작될 수 있는 정보이기 때문에 front, auth 서버와 붙인 후 uuid로 변경해보겠습니다.

2022-07-21 00:37 UTC, JoisFe commented on pom.xml
> +			<version>2.7.0</version>
넵 해당 부분과 lettuce 두 의존성 모두 starter-data-redis 으로 수정하도록 하겠습니다.

2022-07-21 00:38 UTC, JoisFe commented on src/main/java/shop/gaship/gashipgateway/config/RedisConfig.java
> +    private ClassLoader classLoader;
이전에 사용하다 필요 없어졌는데 아직 삭제를 하지 못한 것 같습니다. 해당 부분 삭제하도록 하겠습니다.

2022-07-21 00:39 UTC, JoisFe commented on src/main/java/shop/gaship/gashipgateway/fliter/RequestFilter.java
> +            String accessToken = exchange.getRequest().getHeaders().get("X-AUTH-TOKEN").get(0);
큰 이유는 없습니다. 헤더에 토큰을 담을때 키값을 auth관련 토큰이라는 의미를 보이기 위해 이렇게 정했습니다.

2022-07-21 00:40 UTC, JoisFe commented on src/main/java/shop/gaship/gashipgateway/fliter/RequestFilter.java
> +                throw new LogoutTokenRequestException();
로그인 전 상태에는 해당 필터를 거치지 않기 때문에 문제가 발생하지 않을 것 입니다.

2022-07-21 00:44 UTC, JoisFe commented on src/main/java/shop/gaship/gashipgateway/fliter/RequestFilter.java
> +            Payload payload = config.jwtTokenUtil.getPayloadFromToken(accessToken);
getPayloadFromToken 메서드 과정에서 토큰을 디코딩 하면서 만료기간이 끝난 경우 ExpiredJwtException이 발생하고 그 exception을 핸들링 하는 방식으로 관리를 합니다.

2022-07-21 00:46 UTC, JoisFe commented
black list 체크 후 차단경우 RequestFilter의 50번째 줄에 구현되어 있습니다.

2022-07-21 00:53 UTC, JoisFe commented on src/main/java/shop/gaship/gashipgateway/fliter/RequestFilter.java
> +    public static class Config {
AbstractGatewayFilterFactory 클래스 내부를 보면
public AbstractGatewayFilterFactory(Class<C> configClass) {
        super(configClass);
    }

해당 생성자를 이용해서 RouteLocatorConfig.class 에서 라우팅 중에 필터를 적용할때
requestFilter.apply(new RequestFilter.Config(redisTemplate, jwtTokenUtil))))
으로 합니다.

따라서 RequestFilter 객체를 만들때 Config클래스가 대부분 필요하기 때문에 inner class로 두면 편리하다고 판단하여 이렇게 두었습니다.

2022-07-25 01:15 UTC, JoisFe commented on pom.xml
> +			<groupId>io.lettuce</groupId>
넵 그렇게 수정하겠습니다.

2022-07-25 01:24 UTC, JoisFe commented on src/main/java/shop/gaship/gashipgateway/config/RedisConfig.java
> +@ConfigurationProperties(prefix = "redis")
해당 설정이 default로 알고 있습니다.

2022-07-26 04:41 UTC, merged